# Generated by Django 5.1.6 on 2025-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_comments', models.IntegerField()),
                ('positive_percentage', models.FloatField()),
                ('neutral_percentage', models.FloatField()),
                ('negative_percentage', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
